// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-accounts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "List all financial accounts (conti) belonging to the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("accounts").select("id,name,type,balance,currency,institution,is_active").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { accounts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's transactions, optionally filtered by date range, type, or account.",
  inputSchema: {
    from: z.string().optional().describe("ISO date (YYYY-MM-DD) lower bound, inclusive."),
    to: z.string().optional().describe("ISO date (YYYY-MM-DD) upper bound, inclusive."),
    type: z.enum(["income", "expense"]).optional().describe("Filter by transaction type."),
    account_id: z.string().uuid().optional().describe("Filter by account UUID."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, type, account_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("transactions").select("id,date,amount,type,description,merchant,category_id,account_id,is_categorized").order("date", { ascending: false }).limit(limit);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (type) q = q.eq("type", type);
    if (account_id) q = q.eq("account_id", account_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_transaction_default = defineTool3({
  name: "create_transaction",
  title: "Create transaction",
  description: "Create a new transaction for the signed-in user.",
  inputSchema: {
    date: z2.string().describe("ISO date YYYY-MM-DD."),
    amount: z2.number().describe("Transaction amount in EUR (positive number)."),
    type: z2.enum(["income", "expense"]).describe("Entrata (income) o uscita (expense)."),
    description: z2.string().optional(),
    merchant: z2.string().optional(),
    account_id: z2.string().uuid().optional(),
    category_id: z2.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("transactions").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      amount: input.amount,
      type: input.type,
      description: input.description ?? null,
      merchant: input.merchant ?? null,
      account_id: input.account_id ?? null,
      category_id: input.category_id ?? null,
      is_categorized: !!input.category_id
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Transazione creata: ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "blbeocapuarckgqszhze";
var mcp_default = defineMcp({
  name: "liquido-mcp",
  title: "Liquid\xF2 MCP",
  version: "0.1.0",
  instructions: "Strumenti per Liquid\xF2, l'app di gestione finanziaria per freelance italiani. Usa `list_accounts` per elencare i conti, `list_transactions` per leggere le transazioni (con filtri per data, tipo, conto) e `create_transaction` per registrarne una nuova.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_accounts_default, list_transactions_default, create_transaction_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
